services:
  server:
    build:
      context: . #  Корневой каталог проекта
      dockerfile: server/Dockerfile
    ports:
      - '4000:4000' #  Перенаправляем порт 3000 (или любой, который вы используете) с хоста на контейнер
    #  (Опционально)  Если нужно монтировать код для разработки
    # volumes:
    #   - ./server:/app
    #   - /app/node_modules
    # command: node app.js   #  (По умолчанию)
  client:
    build:
      context: . # Корневой каталог проекта
      dockerfile: Dockerfile
    ports:
      - '80:80' #  Перенаправляем порт 80 (или любой, который вы используете) с хоста на контейнер
    depends_on:
      - server
    #  Зависимость: клиент запускается после сервера (если нужно)
    #  (Опционально)  Если нужен прокси для разработки (например, для Vite):
    # volumes:
    #   - ./client:/app #  Монтируем код, чтобы изменения были видны сразу
    #   - /app/node_modules
    # command: npm run dev #  Используйте команду для запуска dev-сервера Vite
